### ISSUE TITLE
Status code 202 in successful POST response.

### ISSUE THREAD

**Issue by KapsonLabs** [llwasampijja/ireporter-challenge-two#3]
@llwasampijja status code `202` means the request has been accepted for processing but the processing has not yet been completed. Seems to be the code that you are returning as a response to a successful POST request. The `201` on the other hand means the request was successfully processed and the consequent data created in the data store.

Wont the code `202` kinda confuse the user because it doesnt communicate successful data creation.

**Comment by llwasampijja** [comment]
> @llwasampijja status code `202` means the request has been accepted for processing but the processing has not yet been completed. Seems to be the code that you are returning as a response to a successful POST request. The `201` on the other hand means the request was successfully processed and the consequent data created in the data store.
> 
> Wont the code `202` kinda confuse the user because it doesnt communicate successful data creation.

You have a point there, so should I use code 201?

**Comment by KapsonLabs** [comment]
I presume status code `201` is sufficient for this use case.
